name: bureau
channels:
  - conda-forge
dependencies:
  - python==3.10.12
  # - ipywidgets==8.1.1
  # - jupyterlab==4.0.3
  # - langchain==0.0.279
  # - llama-hub==0.0.26
  - llama-index==0.8.19
  - llama-cpp-python==0.1.83
  - matplotlib==3.7.2
  - nltk==3.8.1
  - numpy==1.25.1
  - openai==0.28.0
  - pandas==2.0.3
  - pdfkit==1.0.0
  - plotly==5.16.1
  - pycryptodome==3.18.0
  - pypdf==3.15.5
  - python-environ==0.4.54
  - scikit-learn==1.3.0
  - scipy==1.11.1
  - seaborn==0.12.2
  - sentence-transformers==2.2.2
  - streamlit==1.26.0
  - streamlit-chat==0.1.1
  - streamlit-extras==0.3.2
  - tiktoken==0.4.0

